In [46]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [47]:
#import dataset
df = pd.read_csv("bps_df0722_xm0727.csv")

In [48]:
dis = df[["Disc_Loc","Disc_Type","Disc_Reason"]]
dis

,Disc_Loc,Disc_Type,Disc_Reason
0,无此经历,无此经历,无此经历
1,无此经历,无此经历,无此经历
2,无此经历,无此经历,无此经历
3,无此经历,无此经历,无此经历
4,学校┋公共交通┋商业：杂货店,躲避,种族┋口罩或衣服
...,...,...,...
1217,无此经历,无此经历,种族┋口罩或衣服
1218,学校┋公共交通,工作场所歧视,国籍┋种族
1219,商业：杂货店┋网络平台(如：Facebook、微博、微信、Twitter),躲避┋口头骚扰/被叫带有侮辱性的绰号┋被当面咳嗽/吐口水,国籍┋种族┋口罩或衣服┋留学生身份
1220,公共交通┋线上上课或会议时┋商业：杂货店┋网络平台(如：Facebook、微博、微信、Twi...,躲避┋破坏公共场所/涂鸦,国籍┋语言
1221,公共街道/人行道┋网络平台(如：Facebook、微博、微信、Twitter),躲避┋口头骚扰/被叫带有侮辱性的绰号,国籍┋种族

In [49]:
dis_loc = dis.Disc_Loc.str.split("┋",expand=True,)
dis_loc

,0,1,2,3,4,5,6,7,8,9,10
0,无此经历,None,None,None,None,None,None,None,None,None,None
1,无此经历,None,None,None,None,None,None,None,None,None,None
2,无此经历,None,None,None,None,None,None,None,None,None,None
3,无此经历,None,None,None,None,None,None,None,None,None,None
4,学校,公共交通,商业：杂货店,None,None,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...
1217,无此经历,None,None,None,None,None,None,None,None,None,None
1218,学校,公共交通,None,None,None,None,None,None,None,None,None
1219,商业：杂货店,网络平台(如：Facebook、微博、微信、Twitter),None,None,None,None,None,None,None,None,None
1220,公共交通,线上上课或会议时,商业：杂货店,网络平台(如：Facebook、微博、微信、Twitter),None,None,None,None,None,None,None
1221,公共街道/人行道,网络平台(如：Facebook、微博、微信、Twitter),None,None,None,None,None,None,None,None,None

In [51]:
for i in dis_loc.columns:
    x = dis_loc[i].value_counts()
    print("Column name is:",i,"and it value is:",x)
    print()

Column name is: 0 and it value is: 无此经历                              674
学校                                185
公共街道/人行道                           98
公共交通                               91
网络平台(如：Facebook、微博、微信、Twitter)     78
商业：杂货店                             47
公园                                 14
私人住宅                               12
商业：非杂货店                             8
线上上课或会议时                            6
其他(请注明)：〖无〗                         2
其他(请注明)：〖海关〗                        1
其他(请注明)：〖uber〗                      1
其他(请注明)：〖目前无〗                       1
宗教场所                                1
其他(请注明)：〖Uber〗                      1
其他(请注明)：〖没有〗                        1
其他(请注明)：〖西人租房管理处〗                   1
Name: 0, dtype: int64

Column name is: 1 and it value is: 公共交通                              89
网络平台(如：Facebook、微博、微信、Twitter)    78
公共街道/人行道                          51
商业：杂货店                            29
线上上课或会议时                          14
公园                                13
商业：非杂货店                           10
私人住宅                               5
学校                                 2
其他(请注明)：〖朋友的调侃〗                    1
其他(请注明)：〖Youtube〗                  1
其他(请注明)：〖寄宿家庭的主人〗                  1
宗教场所                               1
Name: 1, dtype: int64

Column name is: 2 and it value is: 网络平台(如：Facebook、微博、微信、Twitter)    41
公共街道/人行道                          40
商业：杂货店                            20
公园                                15
线上上课或会议时                          12
商业：非杂货店                            3
私人住宅                               3
公共交通                               2
宗教场所                               2
其他(请注明)：〖uber上〗                    1
其他(请注明)：〖BMV 等公共场合〗                1
其他(请注明)：〖包括被国内社交平台上的人攻击〗           1
其他(请注明)：〖电梯〗                       1
其他(请注明)：〖联网打游戏时〗                   1
其他(请注明)：〖被中国陌生同学无故团体歧视〗            1
Name: 2, dtype: int64

Column name is: 3 and it value is: 网络平台(如：Facebook、微博、微信、Twitter)    28
商业：杂货店                            11
公共街道/人行道                          11
商业：非杂货店                            9
公园                                 5
私人住宅                               1
线上上课或会议时                           1
其他(请注明)：〖Microaggression 居多〗       1
宗教场所                               1
Name: 3, dtype: int64

Column name is: 4 and it value is: 公共街道/人行道                          11
网络平台(如：Facebook、微博、微信、Twitter)     8
商业：非杂货店                            6
商业：杂货店                             3
私人住宅                               2
公园                                 1
线上上课或会议时                           1
Name: 4, dtype: int64

Column name is: 5 and it value is: 网络平台(如：Facebook、微博、微信、Twitter)    9
公共街道/人行道                          8
商业：非杂货店                           2
商业：杂货店                            2
公园                                1
Name: 5, dtype: int64

Column name is: 6 and it value is: 网络平台(如：Facebook、微博、微信、Twitter)    4
商业：非杂货店                           2
公共街道/人行道                          2
私人住宅                              1
Name: 6, dtype: int64

Column name is: 7 and it value is: 公共街道/人行道                          2
网络平台(如：Facebook、微博、微信、Twitter)    2
商业：杂货店                            1
Name: 7, dtype: int64

Column name is: 8 and it value is: 商业：非杂货店                           1
网络平台(如：Facebook、微博、微信、Twitter)    1
Name: 8, dtype: int64

Column name is: 9 and it value is: 公共街道/人行道    1
Name: 9, dtype: int64

Column name is: 10 and it value is: 网络平台(如：Facebook、微博、微信、Twitter)    1
Name: 10, dtype: int64

In [59]:
dis_type = dis.Disc_Type.str.split("┋",expand=True,)
dis_type

           0                1          2     3     4
0       无此经历             None       None  None  None
1       无此经历             None       None  None  None
2       无此经历             None       None  None  None
3       无此经历             None       None  None  None
4         躲避             None       None  None  None
...      ...              ...        ...   ...   ...
1217    无此经历             None       None  None  None
1218  工作场所歧视             None       None  None  None
1219      躲避  口头骚扰/被叫带有侮辱性的绰号  被当面咳嗽/吐口水  None  None
1220      躲避        破坏公共场所/涂鸦       None  None  None
1221      躲避  口头骚扰/被叫带有侮辱性的绰号       None  None  None

[1222 rows x 5 columns]

In [60]:
for i in dis_type.columns:
    x = dis_type[i].value_counts()
    print("Column name is:",i,"and it value is:",x)
    print()

Column name is: 0 and it value is: 无此经历                                                         703
口头骚扰/被叫带有侮辱性的绰号                                              260
躲避                                                           198
被当面咳嗽/吐口水                                                      9
工作场所歧视                                                         8
破坏公共场所/涂鸦                                                      6
禁止行驶或被拒载(如：Lyft，Uber，公共交通)                                     2
其他(请注明)：〖Be framed due to race. Be cursed due to atheist〗      1
其他(请注明)：〖社交网络〗                                                 1
其他(请注明)：〖他人之间进行的不针对我的讨论，但发表在公共平台上被我看见〗                         1
其他(请注明)：〖从车上竖中指〗                                               1
其他(请注明)：〖verbal attack〗                                        1
其他(请注明)：〖上课，考试〗                                                1
其他(请注明)：〖被要求不能带口罩 否则拒绝服务〗                                      1
其他(请注明)：〖言语攻击〗                                                 1
其他(请注明)：〖被泼水〗                                                  1
其他(请注明)：〖插队〗                                                   1
其他(请注明)：〖网络骂战〗                                                 1
其他(请注明)：〖感觉在语言上被歧视〗                                            1
其他(请注明)：〖没有〗                                                   1
其他(请注明)：〖无〗                                                    1
其他(请注明)：〖被问中国人是不是都吃蝙蝠〗                                         1
其他(请注明)：〖眼光异样〗                                                 1
其他(请注明)：〖刻意阻拦 无理由延误〗                                           1
其他(请注明)：〖找理由不给办会员〗                                             1
其他(请注明)：〖被教授区别对待 不认可能力等〗                                       1
其他(请注明)：〖被无礼对待〗                                                1
其他(请注明)：〖being asked if we were in China〗                      1
其他(请注明)：〖口头诋毁〗                                                 1
其他(请注明)：〖被要求消毒〗                                                1
其他(请注明)：〖冲着我喊：你们中国人把新冠带到美国〗                                    1
身体骚扰                                                           1
其他(请注明)：〖不愿意进行团队合作〗                                            1
其他(请注明)：〖态度较差〗                                                 1
其他(请注明)：〖被白人在超市里教训要离他远一点〗                                      1
其他(请注明)：〖当面说你们中国应该关闭所有市场因为病毒是在那儿爆发的〗                           1
其他(请注明)：〖教授因非母语者原因强行拒绝为作文打分并要求不断重写〗                            1
其他(请注明)：〖对戴口罩者的异样眼神和粗鲁态度〗                                      1
其他(请注明)：〖用异样的眼光看戴口罩的我〗                                         1
其他(请注明)：〖增加入关审查〗                                               1
其他(请注明)：〖开车恐吓〗                                                 1
其他(请注明)：〖分数评判〗                                                 1
其他(请注明)：〖微博无脑歧视留学生〗                                            1
Name: 0, dtype: int64

Column name is: 1 and it value is: 口头骚扰/被叫带有侮辱性的绰号                        90
被当面咳嗽/吐口水                              23
工作场所歧视                                 15
破坏公共场所/涂鸦                               9
禁止行驶或被拒载(如：Lyft，Uber，公共交通)              6
身体骚扰                                    5
躲避                                      5
其他(请注明)：〖网民喷人〗                          1
其他(请注明)：〖寄宿家庭主人说中国不好，说中国学生不好，说的很难听〗     1
其他(请注明)：〖收银员接待时的态度突然转变〗                 1
其他(请注明)：〖要钱和辱骂〗                         1
其他(请注明)：〖被模仿戴口罩的样子〗                     1
其他(请注明)：〖网暴〗                            1
Name: 1, dtype: int64

Column name is: 2 and it value is: 身体骚扰                          8
工作场所歧视                        8
被当面咳嗽/吐口水                     6
禁止行驶或被拒载(如：Lyft，Uber，公共交通)    6
破坏公共场所/涂鸦                     4
其他(请注明)：〖不是疫情期间〗              1
其他(请注明)：〖网络留言〗                1
Name: 2, dtype: int64

Column name is: 3 and it value is: 禁止行驶或被拒载(如：Lyft，Uber，公共交通)    2
工作场所歧视                        1
破坏公共场所/涂鸦                     1
Name: 3, dtype: int64

Column name is: 4 and it value is: 禁止行驶或被拒载(如：Lyft，Uber，公共交通)    1
破坏公共场所/涂鸦                     1
Name: 4, dtype: int64

In [61]:
dis_reason = dis.Disc_Reason.str.split("┋",expand=True,)
dis_reason

         0      1      2      3     4     5     6     7
0     无此经历   None   None   None  None  None  None  None
1     无此经历   None   None   None  None  None  None  None
2     无此经历   None   None   None  None  None  None  None
3     无此经历   None   None   None  None  None  None  None
4       种族  口罩或衣服   None   None  None  None  None  None
...    ...    ...    ...    ...   ...   ...   ...   ...
1217    种族  口罩或衣服   None   None  None  None  None  None
1218    国籍     种族   None   None  None  None  None  None
1219    国籍     种族  口罩或衣服  留学生身份  None  None  None  None
1220    国籍     语言   None   None  None  None  None  None
1221    国籍     种族   None   None  None  None  None  None

[1222 rows x 8 columns]

In [62]:
for i in dis_reason.columns:
    x = dis_reason[i].value_counts()
    print("Column name is:",i,"and it value is:",x)
    print()

Column name is: 0 and it value is: 无此经历                   598
国籍                     338
种族                     165
不确定                     58
口罩或衣服                   31
留学生身份                   14
语言                       5
性别                       3
其他(请注明)：〖身材〗             1
其他(请注明)：〖没有〗             1
食品                       1
其他(请注明)：〖年龄〗             1
其他(请注明)：〖怕是病毒携带者〗        1
其他(请注明)：〖使用华为手机〗         1
其他(请注明)：〖学习比他们好...〗      1
其他(请注明)：〖带宠物上Uber〗       1
其他(请注明)：〖体重〗             1
其他(请注明)：〖自身不良行为〗         1
Name: 0, dtype: int64

Column name is: 1 and it value is: 种族                279
口罩或衣服              80
语言                 27
留学生身份              25
国籍                 25
性别                 16
不确定                 6
宗教                  2
其他(请注明)：〖亚洲面孔〗      1
其他(请注明)：〖事后反应〗      1
Name: 1, dtype: int64

Column name is: 2 and it value is: 口罩或衣服             84
语言                69
留学生身份             57
性别                35
种族                16
其他(请注明)：〖文化差异〗     1
Name: 2, dtype: int64

Column name is: 3 and it value is: 留学生身份               53
口罩或衣服               46
语言                  23
性别                   5
食品                   1
其他(请注明)：〖武汉人的身份〗     1
宗教                   1
Name: 3, dtype: int64

Column name is: 4 and it value is: 留学生身份    39
口罩或衣服     7
语言        2
宗教        2
Name: 4, dtype: int64

Column name is: 5 and it value is: 留学生身份             6
食品                2
口罩或衣服             1
其他(请注明)：〖意识形态〗    1
Name: 5, dtype: int64

Column name is: 6 and it value is: 口罩或衣服    2
留学生身份    1
Name: 6, dtype: int64

Column name is: 7 and it value is: 留学生身份    2
Name: 7, dtype: int64